#define PATCHLEVEL 1
#define PATCHLEVEL_MINOR 1
#define PATCHLEVEL_SUBMINOR 16
#define PATCHLEVEL_RELEASE_KIND "alpha"
#ifndef PATCHLEVEL_RELEASE_DATE 
#ifdef RELEASE_DATE
#define PATCHLEVEL_RELEASE_DATE RELEASE_DATE
#else
#define PATCHLEVEL_RELEASE_DATE "$Date: 2006-02-20 14:58:34 $"
#endif
#ifndef CONFIGURE_OPTIONS
#define CONFIGURE_OPTIONS ""
#endif
#endif
